apiVersion: apps/v1
kind: Deployment
metadata:
  name: http_service
spec:
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: http_service
  template:
    metadata:
      labels:
        app: http_service
    spec:
      containers:
        - name: http_service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3030

