name: Build and Push Image

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #Get the code
      - name: Checkout
        uses: actions/checkout@v4

      #Set up Docker
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      #Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #Compute Git SHA
      - name: Get SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      #Build + Push Image
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./apps/http_service/
          push: true
          tags: ghcr.io/jarom-w/http_service:${{ steps.vars.outputs.sha }}

  promote-dev:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: jarom-w/promote_pipeline
          token: ${{ secrets.GITOPS_TOKEN }}
          
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update dev image tag
        run: |
          yq -i '.image.tag = strenv(SHA)' environments/http_service/dev/http-service.yaml
        env:
          SHA: ${{ env.SHA }}

      - name: Commit change to dev image tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m " Update dev image to ${{ steps.vars.outputs.sha }}"

      #Build + Push Image
      - name: Push branch
        run: |
          git push
        env:
          GH_TOKEN: ${{ secrets.GITOPS_TOKEN }}
